command:
  anti-syntax-message: "&cYou cannot execute {argument}."
  syntax-bypass-perm: "PluginBase.owner"

on-join:
  teleport:
    location:
      world: world
      x: 0.5
      y: 73.0
      z: 0.5
      yaw: 90.0
      pitch: 0.0