debugging: true

command:
  anti-syntax-message: "&cYou cannot execute {argument}."
  syntax-bypass-perm: "alley.owner"
  grant-cosmetic-permission-command: "permission set {player} {permission}"

spawn:
  # The spawn location of the server
  join-location: world:0.5:73.0:0.5:90.0:0.0

arena:
  # When creating an arena, the following displayname for each
  # arena type will be set. {arena} represents the arena name.
  default-display-name:
    shared: "&b{arena}"
    standalone: "&b{arena}"
    ffa: "&b{arena}"
