command:
  anti-syntax-message: "&cYou cannot execute {argument}."
  syntax-bypass-perm: "alley.owner"
  grant-cosmetic-permission-command: "permission set {player} {permission}"

spawn:
  # The spawn location of the server
  join-location: world:0.5:73.0:0.5:90.0:0.0
